version: "3.1"
services:
  db:
    image: postgres
    container_name: postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - 5432:5432
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: